### ISSUE TITLE
Error with type inference in drift 2.0

### ISSUE THREAD

**Issue by davidmartos96** [simolus3/moor#1991]
Hello Simon,
I've just updated to use drift 2.0 and I encountered with a very curious failing test in my test suite.

The following test in the `integration_tests/select_integration_test.dart` file fails with the following error: 
```
Invalid argument(s): Could not find a matching SQL type for Never
DriftSqlType.forType
package:drift/…/types/mapping.dart:253
QueryRow.readNullable
package:drift/…/select/custom_select.dart:97
QueryRow.read
package:drift/…/select/custom_select.dart:82
main.getCategoryIdByDescription
test/integration_tests/select_integration_test.dart:41
===== asynchronous gap ===========================
main.<fn>
```

```dart
  Future<int?> getCategoryIdByDescription(TodoDb appDatabase, String description) async {
    const q = "SELECT id FROM categories WHERE desc = ?";
    final row = await appDatabase.customSelect(
      q,
      variables: [Variable<String>(description)],
    ).getSingleOrNull();
    return row?.read("id");
  }

  test('failing', () async {
    final categoryDescription = 'category description';
    await db.categories.insertOne(CategoriesCompanion.insert(description: categoryDescription));

    // Search the category we just inserted
    final categoryId = await getCategoryIdByDescription(db, categoryDescription);

    expect(categoryId != null, true);
  });
```

It seems to be due to the type inference in the line 
`return row?.read("id");`

If we change that into the following it works ok
```dart
final id = row?.read<int>("id");
return id;
```

I don't know if this is fixable in here or if it is a bug in the Dart SDK, but this wasn't failing in previous versions of drift.

Let's hope this has a solution, since this would be very hard to catch in existing code as it only fails in runtime.

**Comment by simolus3** [comment]
This is very unfortunate indeed :(

The problem appears to be that `read` is now declared with a non-nullable type parameter which is causing the inference failure. I think this is probably a bug in the SDK and I have opened https://github.com/dart-lang/language/issues/2409 to track it. It's very weird that this only happens on async functions.

I'll also try to find a way to revert this restriction now.

**Comment by simolus3** [comment]
Fixed in 7de1b5aef10511ed57cb8ef0a7fcb1908083d8d3!

**Comment by davidmartos96** [comment]
Great to hear! Thanks Simon 😄

**Comment by davidmartos96** [comment]
@simolus3 Maybe this needs to be reopened? I'm still seeing the test from above fail in the drift repository with 2.0.2 but no crash with 1.x.
Now the error is not the "Never" type not found, but "Future<int?>" :sweat_smile:

**Comment by simolus3** [comment]
You're right. I thought the issue with the type inference to `Never` was the only problem (and I've added tests for that), but now it just fails one layer further down.

Your snippet works with 2d75e1fd621d77e0e1807ba0d555f844cdc7640d. Could you try out that version in your app and let me know if you run into any other issues like this? I think the fix should restore the old behavior entirely now, but I want to make sure I'm not overlooking something :D

```yaml
dependency_overrides:
  drift:
    git:
      url: https://github.com/simolus3/drift.git
      ref: 2d75e1fd621d77e0e1807ba0d555f844cdc7640d
      path: drift
```

**Comment by davidmartos96** [comment]
@simolus3 Yes, it works fine in that commit

**Comment by simolus3** [comment]
Fixed in `drift` version `2.0.2+1` which I have just released.
