### ISSUE TITLE
Bug: Code Generation for UNION ALL with CTE

### ISSUE THREAD

**Issue by jakobhec** [simolus3/moor#2492]
I cannot make code generation work for queries that use a CTE and UNION ALL.

Here is a small example `tables.drift` file: 
```sql
CREATE TABLE items (
    id INT NOT NULL PRIMARY KEY
);

queryCteWithUnionAll:
WITH filtered_items AS (
    SELECT *
    FROM items
    -- WHERE ...
)
select null as category
FROM filtered_items
UNION ALL 
SELECT null as category
FROM filtered_items;
```

Running `dart run drift_dev analyze`:
```bash
dart run drift_dev analyze
WARNING: Could not analyze DriftElementId(package:my_app/drift/tables.drift, queryCteWithUnionAll)Null check operator used on a null value
#0      ColumnResolver._handle.<anonymous closure> (package:sqlparser/src/analysis/steps/column_resolver.dart:296:54)
#1      Queryable.when (package:sqlparser/src/ast/common/queryables.dart:14:21)
#2      ColumnResolver._handle (package:sqlparser/src/analysis/steps/column_resolver.dart:289:15)
#3      ColumnResolver._resolveSelect (package:sqlparser/src/analysis/steps/column_resolver.dart:349:7)
...
```

Using `dart run build_runner build`:
```bash
Executing task: /Applications/Development/flutter/bin/cache/dart-sdk/bin/dart run build_runner build 

Building package executable... (3.7s)
Built build_runner:build_runner.
[INFO] Generating build script completed, took 202ms
[INFO] Reading cached asset graph completed, took 571ms
[INFO] Checking for updates since last build completed, took 900ms

[WARNING] drift_dev on lib/drift/tables.drift:
Could not analyze DriftElementId(package:my_app/drift/tables.drift, queryCteWithUnionAll)
Null check operator used on a null value
[INFO] Running build completed, took 26.6s
[INFO] Caching finalized dependency graph completed, took 424ms
[INFO] Succeeded after 27.0s with 17 outputs (18 actions)
```

In the `pubspec.yaml`:
```yaml
dependencies:
  drift: ^2.9.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.3

dev_dependencies:
  drift_dev: ^2.9.0
  build_runner: ^2.4.5
```

**My Use Case:**
I would like to recreate the [GROUPING SETS feature from PostgreSQL](https://www.postgresqltutorial.com/postgresql-tutorial/postgresql-grouping-sets/). Slightly larger example:
```sql
CREATE TABLE items (
    id INT NOT NULL PRIMARY KEY AUTOINCREMENT,
    content TEXT NOT NULL,
    category INTEGER NOT NULL,
    theme INTEGER NOT NULL
);


queryCteWithUnionAll:
WITH filtered_items AS (
    SELECT *
    FROM items
    WHERE content like '*hello*'
)
select category, null as theme, COUNT(*) AS count_items
FROM filtered_items
GROUP BY category
UNION ALL 
SELECT null as category, theme, COUNT(*) AS count_items
FROM filtered_items
GROUP BY theme;
```

If there are any workarounds or better solutions that currently work, please let me know!

**Comment by simolus3** [comment]
Excellent report, thanks for the helpful example! :+1: 

This bug has been fixed in c700b5b4becb1e6af5205dc90dde0d0a17c32c44 which has also been released to pub.dev with `sqlparser: 0.30.3`. So a `dart pub upgrade` should fix this issue.

**Comment by jakobhec** [comment]
Awesome, that was super fast. Thank you! 

I ran `dart pub upgrade` and now use `sqlparser: 0.30.3`.

`dart run drift_dev analyze` seems to work: 
```bash
dart run drift_dev analyze                       
Building package executable... (3.9s)
Built drift_dev:drift_dev.
INFO: No errors found
```

But `dart run build_runner build` still shows the same issue: 
```bash
Executing task: /Applications/Development/flutter/bin/cache/dart-sdk/bin/dart run build_runner build 

Building package executable... (3.4s)
Built build_runner:build_runner.
[INFO] Generating build script completed, took 196ms
[INFO] Reading cached asset graph completed, took 555ms
[INFO] Checking for updates since last build completed, took 838ms

[WARNING] drift_dev on lib/drift/tables.drift:
Could not analyze DriftElementId(package:my_app/drift/tables.drift, queryCteWithUnion)
Null check operator used on a null value
[INFO] Running build completed, took 25.5s
[INFO] Caching finalized dependency graph completed, took 423ms
[INFO] Succeeded after 25.9s with 17 outputs (16 actions)
 *  Terminal will be reused by tasks, press any key to close it. 
```

**Comment by simolus3** [comment]
Could you try a `dart run build_runner clean` (warning: that can delete generated code too) followed by `dart run build_runner build -d` to regenerate it?

**Comment by jakobhec** [comment]
That works! Thanks a lot
