### ISSUE TITLE
migration_test.dart fails when migrate to TEXT representation of datetime

### ISSUE THREAD

**Issue by rubiktubik** [simolus3/moor#3619]
**Describe the bug**

I have an existing sqlite Datebase which has datetime columns and uses the default Unix Timestamps behavior.

Now i want to migrate to `ISO-8601 Strings` like written in https://drift.simonbinder.eu/guides/datetime-migrations/ 

I'am using the automatic migration with `make migration` command AND modular generation. 
I'am using drift 2.26 and drift_dev 2.26

The migration itself works but all tests in the generated `migration_test.dart` fail.

https://github.com/simolus3/drift/issues/3066

My step:
1. Modified build.yaml
```yaml
targets:
  $default:
    builders:
      drift_dev:
        # disable drift's default builder, we're using the modular setup
        # instead.
        enabled: false
        options:
          store_date_time_values_as_text: true

      # Instead, enable drift_dev:analyzer and drift_dev:modular manually:
      drift_dev:analyzer:
        enabled: true
        options: &options
          store_date_time_values_as_text: true
          databases:
            # Required: A name for the database and it's path
            my_database: lib/environment/database/sync_database.dart
          sql:
            dialects:
              - sqlite
      drift_dev:modular:
        enabled: true
        options: *options
```

2. Run `dart run build_runner build --delete-conflicting-outputs`
The sync_database.drift.dart file now contains:
```dart
@override
  i0.DriftDatabaseOptions get options =>
      const i0.DriftDatabaseOptions(storeDateTimeAsText: true);
```
3. Now run `dart run drift_dev make-migrations`
Getting the expected error to increase the schema version
4. Increase schema version

<img width="647" height="61" alt="Image" src="https://github.com/user-attachments/assets/1e6f1b50-252c-4799-8044-0bb566fb4bd0" />

5. run `dart run drift_dev make-migrations` again
The code-generator creates a new `from6To7` function

6. Add the migration code.
Add 
```dart
Future<void> migrateFromUnixTimestampsToText(Migrator m) async {
  for (final table in allTables) {
    final dateTimeColumns =
        table.$columns.where((c) => c.type == DriftSqlType.dateTime);

    if (dateTimeColumns.isNotEmpty) {
      // This table has dateTime columns which need to be migrated.
      await m.alterTable(TableMigration(
        table,
        columnTransformer: {
          for (final column in dateTimeColumns)
            // We assume that the column in the database is an int (unix
            // timestamp), use `fromUnixEpoch` to convert it to a date time.
            // Note that the resulting value in the database is in UTC.
            column: DateTimeExpressions.fromUnixEpoch(column.dartCast<int>()),
        },
      ));
    }
  }
}
```
Then call `migrateFromUnixTimestampsToText`
<img width="430" height="65" alt="Image" src="https://github.com/user-attachments/assets/854f64a6-251f-4e36-884a-90164547206b" />
7. Run `flutter test test/drift/my_database/migration_test.dart`
Getting errors like this:
The older migrations 1 to 2, 1 to 3, 2 to 3 and so on are getting errors. 

<img width="416" height="338" alt="Image" src="https://github.com/user-attachments/assets/5fdbe0f8-3098-4c67-a114-79167f985635" />

The tests for the newest migration from 1,2,3,4,5,6 to 7 works (is is expected)
<img width="437" height="150" alt="Image" src="https://github.com/user-attachments/assets/1fc1ff93-5d13-4e3c-bf80-32bbf70df927" />

Migrations like 1 to 2 did not had the `store_date_time_values_as_text = true` why are they failing? Is this a bug?

Great library btw. 

Best regards
Michael

**Comment by devroble** [comment]
Hi @rubiktubik,
Have you seen the discussion here: ?
It looks like your issue might have been addressed there.

https://github.com/simolus3/drift/discussions/3603#discussioncomment-13743055

**Comment by simolus3** [comment]
Hi, thanks for the report. Your approach of running the command seems correct to me, but I agree with the suggestion of replacing `for (final table in allTables)` with `for (final table in schema.entities.whereType<TableInfo>())`, where `schema` is the second argument to the `fromXToY` callback. Does that fix the issue for you?

**Comment by rubiktubik** [comment]
Thank you for your responses @devroble  @simolus3 

I have tried:

```dart
Future<void> migrateFromUnixTimestampsToText(
      Migrator m, Schema7 schema) async {
    for (final table in schema.entities.whereType<TableInfo>()) {
      final dateTimeColumns =
          table.$columns.where((c) => c.type == DriftSqlType.dateTime);

      if (dateTimeColumns.isNotEmpty) {
        // This table has dateTime columns which need to be migrated.
        await m.alterTable(TableMigration(
          table,
          columnTransformer: {
            for (final column in dateTimeColumns)
              // We assume that the column in the database is an int (unix
              // timestamp), use `fromUnixEpoch` to convert it to a date time.
              // Note that the resulting value in the database is in UTC.
              column: DateTimeExpressions.fromUnixEpoch(column.dartCast<int>()),
          },
        ));
      }
    }
  }
```

But i get still getting failed tests:

<img width="523" height="346" alt="Image" src="https://github.com/user-attachments/assets/439477d9-f799-4204-bd4d-dc9a75ca2b89" />

1 to 7, 2 to 7, 3 to 7, 4 to 7, 5 to 7 and 6 to 7 seems to work right

<img width="446" height="183" alt="Image" src="https://github.com/user-attachments/assets/6eae7524-6081-4f4f-aea1-79ad1ef4ff86" />

EDIT: oh see that i forgotten to do the "create legacy table with INTEGER timestamps" is there a possibility to print the sql create statement, so that i don't need to write the whole sql create statements manually?

**Comment by rubiktubik** [comment]
The Solution in #3603 solved my issues. Thanks @devroble
